name: Playwright Behave CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 2 * * *'  

jobs:
  test:
    runs-on: self-hosted
    env:
      RUNNER_TOOL_CACHE: /Users/ranaabidi/.cache/tools

    steps:
      - name:  Checkout repository
        uses: actions/checkout@v3

      - name:  Use system Python
        run: python3 --version

      - name:  Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name:  Install Playwright browsers
        run: |
          python3 -m playwright install --with-deps

      - name:  Run all Behave features
        run: |
          mkdir -p reports
          behave features/ --no-capture --format json.pretty --outfile reports/cucumber_report.json

      - name:  Update Excel test report
        run: |
          python3 utils/excel_updater.py

      - name:  Generate test dashboard
        run: |
          python3 utils/playwright_dashboard.py

      - name:  Upload reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            reports/
